---
plan:
    key: DNSPROXY
    name: dnsproxy - Build and run tests
    project-key: GO
variables:
    dockerGo: 'golang:1.19.10'
    dockerLint: golangci/golangci-lint:v1.53
version: 2

stages:
  - Lint:
        final: false
        jobs:
          - Lint
        manual: false
  - Tests:
        final: false
        jobs:
          - Test
        manual: false

Lint:
    docker:
        image: ${bamboo.dockerLint}
        volumes:
            ${system.GO_CACHE_DIR}: "${bamboo.cacheGo}"
            ${system.GO_PKG_CACHE_DIR}: "${bamboo.cacheGoPkg}"
            ${bamboo.build.working.directory}: "/app"
    key: LINT
    other:
        clean-working-dir: true
    requirements:
      - adg-docker: true
    tasks:
      - checkout:
            force-clean-build: true
      - script:
            interpreter: SHELL
            scripts:
              - |
                set -e -f -u -x

                golangci-lint --version
                golangci-lint run -v

Test:
    docker:
        image: ${bamboo.dockerGo}
        volumes:
            ${system.YARN_DIR}: ${bamboo.cacheYarn}
            ${system.GO_CACHE_DIR}: ${bamboo.cacheGo}
            ${system.GO_PKG_CACHE_DIR}: ${bamboo.cacheGoPkg}
    final-tasks:
      - clean
    key: TEST
    requirements:
      - adg-docker: true
    tasks:
      - checkout:
            force-clean-build: true
      - script:
            interpreter: SHELL
            environment: GOFLAGS="-buildvcs=false" CI="1"
            scripts:
              - |
                set -e -f -u -x

                go env
                go version

                make VERBOSE=1 test

branches:
    create: for-pull-request
    delete:
        after-deleted-days: 1
        after-inactive-days: 5
    link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
            name: Build webhook
            url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
    concurrent-build-plugin: system-default
